spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 965999691956-p90targvpar84ahoppos3c11lqcab4e8.apps.googleusercontent.com
          clientSecret: eioNq1OB9uWoWVkxwScSu40u
          scope:
           - email
           - profile
           - calendar
server:
  port: 8080